"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Eye, EyeOff, LockKeyhole, Mail, MoveRight, Phone, UserRound } from "lucide-react";
import AuthLayout from "@/components/auth/AuthLayout";

export default function RegistroPage() {
  const router = useRouter();
  const [nombre, setNombre] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [telefono, setTelefono] = useState(""); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState<string | null>(null); const [isLoading, setIsLoading] = useState(false);
  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); setIsLoading(true); try { const response = await fetch("/api/auth/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ nombre, email, password, telefono }) }); const data = await response.json(); if (!response.ok) return setError(data.error || "No pudimos crear tu cuenta."); router.push("/dashboard"); router.refresh(); } catch { setError("No pudimos conectar. Intentá nuevamente."); } finally { setIsLoading(false); } }
  return <AuthLayout eyebrow="Crear una cuenta" title={<>Empezá tu<br /><span>experiencia.</span></>} description="Registrate una sola vez y reservá tus próximas visitas en minutos."><form className="auth-form" onSubmit={handleSubmit}><label className="auth-label"><span>Nombre completo</span><div className="auth-input-wrap"><UserRound size={18} /><input value={nombre} onChange={(event) => setNombre(event.target.value)} type="text" autoComplete="name" placeholder="Tu nombre y apellido" required /></div></label><label className="auth-label"><span>Email</span><div className="auth-input-wrap"><Mail size={18} /><input value={email} onChange={(event) => setEmail(event.target.value)} type="email" autoComplete="email" placeholder="nombre@email.com" required /></div></label><label className="auth-label"><span>Teléfono <i>Opcional</i></span><div className="auth-input-wrap"><Phone size={18} /><input value={telefono} onChange={(event) => setTelefono(event.target.value)} type="tel" autoComplete="tel" placeholder="+598 99 000 000" maxLength={30} /></div></label><label className="auth-label"><span>Contraseña</span><div className="auth-input-wrap"><LockKeyhole size={18} /><input value={password} onChange={(event) => setPassword(event.target.value)} type={showPassword ? "text" : "password"} autoComplete="new-password" placeholder="Mínimo 8 caracteres" minLength={8} required /><button type="button" aria-label={showPassword ? "Ocultar contraseña" : "Mostrar contraseña"} onClick={() => setShowPassword((value) => !value)}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label>{error && <p role="alert" className="auth-error">{error}</p>}<button type="submit" disabled={isLoading} className="auth-submit">{isLoading ? "Creando cuenta..." : <>Crear mi cuenta <MoveRight size={18} /></>}</button></form><p className="auth-switch">¿Ya tenés una cuenta? <Link href="/login">Iniciá sesión</Link></p></AuthLayout>;
}
