"use client";

import React from "react";

type ReservaAdmin = { id: string; fecha: string; hora: string; estado: string; usuarioId: string; service: { nombre: string }; barber: { nombre: string }; usuario?: { nombre: string; email: string; telefono?: string | null }; notas?: string | null };
function today() { const now = new Date(); return new Date(now.getTime() - now.getTimezoneOffset() * 60_000).toISOString().slice(0, 10); }

export default function ReservationsAdmin({ initial }: { initial: ReservaAdmin[] }) {
  const [items, setItems] = React.useState<ReservaAdmin[]>(initial || []); const [editingId, setEditingId] = React.useState<string | null>(null); const [date, setDate] = React.useState(""); const [time, setTime] = React.useState(""); const [slots, setSlots] = React.useState<string[]>([]); const [loadingSlots, setLoadingSlots] = React.useState(false);
  async function action(id: string, actionName: string) { if (!confirm(`Confirmar acción ${actionName} sobre la reserva?`)) return; try { const response = await fetch("/api/admin/reservas/action", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reservaId: id, action: actionName }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setItems((previous) => previous.map((item) => item.id === id ? { ...item, estado: data.reserva.estado } : item)); } catch { alert("No se pudo actualizar la reserva."); } }
  async function loadSlots(reservaId: string, nextDate: string) { setDate(nextDate); setTime(""); setSlots([]); setLoadingSlots(true); try { const response = await fetch(`/api/admin/reservas/available?${new URLSearchParams({ reservaId, date: nextDate })}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSlots(data.slots ?? []); } catch { alert("No se pudo consultar la disponibilidad."); } finally { setLoadingSlots(false); } }
  function beginEdit(reservation: ReservaAdmin) { setEditingId(reservation.id); void loadSlots(reservation.id, reservation.fecha.slice(0, 10)); }
  async function saveEdit(id: string) { if (!time) return alert("Elegí uno de los horarios disponibles."); try { const response = await fetch("/api/admin/reservas/update", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reservaId: id, date, time }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setItems((previous) => previous.map((item) => item.id === id ? { ...item, fecha: data.reserva.fecha, hora: data.reserva.hora, estado: data.reserva.estado } : item)); setEditingId(null); } catch (cause) { alert(cause instanceof Error ? cause.message : "No se pudo reprogramar la reserva."); } }
  if (!items.length) return <div className="rounded border border-gray-800 bg-gray-900 p-4 text-gray-300">No hay reservas.</div>;
  return <div className="space-y-3">{items.map((reservation) => <div key={reservation.id} className="rounded border border-gray-800 bg-gray-900 p-3"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><div className="text-sm text-gray-300">{new Date(reservation.fecha).toLocaleDateString("es-UY", { timeZone: "UTC" })} · {reservation.hora}</div><div className="text-sm text-white">{reservation.service.nombre} — {reservation.barber.nombre}</div><div className="text-sm text-gray-300">Cliente: {reservation.usuario?.nombre ?? reservation.usuarioId}</div><div className="text-sm text-gray-400">Email: {reservation.usuario?.email ?? "Sin email"}{reservation.usuario?.telefono ? ` · Tel: ${reservation.usuario.telefono}` : ""}</div>{reservation.notas && <div className="mt-1 text-sm text-gray-300">Notas: {reservation.notas}</div>}</div><div className="flex flex-wrap items-center gap-2"><button onClick={() => beginEdit(reservation)} className="rounded bg-blue-700 px-2 py-1 text-sm text-white">Reprogramar</button>{reservation.estado === "PENDIENTE" && <button onClick={() => void action(reservation.id, "confirmar")} className="rounded bg-green-600 px-2 py-1 text-sm text-white">Confirmar</button>}{["PENDIENTE", "CONFIRMADA"].includes(reservation.estado) && <button onClick={() => void action(reservation.id, "cancelar")} className="rounded bg-red-600 px-2 py-1 text-sm text-white">Cancelar</button>}{reservation.estado === "CONFIRMADA" && <button onClick={() => void action(reservation.id, "finalizar")} className="rounded bg-yellow-600 px-2 py-1 text-sm text-black">Finalizar</button>}</div></div>{editingId === reservation.id && <div className="mt-3 grid gap-2 border-t border-gray-800 pt-3 md:grid-cols-[210px_1fr_auto]"><label className="grid gap-1 text-sm text-gray-300">Fecha<input type="date" min={today()} value={date} onChange={(event) => void loadSlots(reservation.id, event.target.value)} className="rounded bg-black p-2 text-white" /></label><label className="grid gap-1 text-sm text-gray-300">Horarios disponibles<select disabled={loadingSlots || !slots.length} value={time} onChange={(event) => setTime(event.target.value)} className="rounded bg-black p-2 text-white disabled:opacity-50"><option value="">{loadingSlots ? "Consultando..." : slots.length ? "Elegí un horario" : "Sin horarios disponibles"}</option>{slots.map((slot) => <option key={slot} value={slot}>{slot}</option>)}</select></label><div className="flex items-end gap-2"><button onClick={() => void saveEdit(reservation.id)} disabled={!time} className="rounded bg-[var(--gold)] px-3 py-2 text-sm font-medium text-black disabled:opacity-50">Guardar</button><button onClick={() => setEditingId(null)} className="rounded border border-gray-600 px-3 py-2 text-sm text-white">Cancelar</button></div><p className="text-xs text-gray-400 md:col-span-3">Solo se muestran turnos libres: lunes a sábado, 08:00–12:30 y 14:30–19:30, en bloques de 45 minutos.</p></div>}</div>)}</div>;
}
